### ISSUE TITLE
how to cite this tool

### ISSUE THREAD

**Issue by cliang-huanglab** [DavisLaboratory/vissE#9]
Hello,author,I am very interested in your tool. Can you provide relevant paper for publishing this tool!

**Comment by bhuvad** [comment]
Hi,

We are in the process of preparing the manuscript for the tool and should be ready with that by the end of the month. We may push it to bioRxiv then but in the meantime, I suggest you use the bioconductor package citation. Once the manuscript is online, I will update you and you can then replace the citation.

https://bioconductor.org/packages/release/bioc/html/vissE.html

Cheers,
Dharmesh
